# Generated by Django 5.0.6 on 2026-07-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "features",
                    models.JSONField(
                        help_text="Raw model input features as key-value pairs"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FraudPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fraud_score",
                    models.FloatField(
                        help_text="Model's raw probability/anomaly score, 0-1"
                    ),
                ),
                ("is_flagged", models.BooleanField(default=False)),
                ("model_version", models.CharField(default="v1", max_length=50)),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("confirmed_fraud", "Confirmed Fraud"),
                            ("false_positive", "False Positive"),
                        ],
                        default="unreviewed",
                        max_length=20,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction",
                        to="fraud_api.transaction",
                    ),
                ),
            ],
        ),
    ]
